label: "p — Paragraph"
order: 1
notes: |
  The `p` element represents a paragraph.
context:
  content: The little kitten gently seated itself on a piece of carpet. Later in his life, this would be referred to as the time the cat sat on the mat.
