label: "Unordered list"
order: 6
notes: |
  The `ul` element represents a list of items, where the order of the items is not important – that is, where changing the order would not materially change the meaning of the document.
context:
  items:
    - content: Switzerland
    - content: United Kingdom
    - content: United States
    - content: Norway
