label: "dl — Description list"
order: 8
notes: |
  The `dl` element represents an association list consisting of zero or more name-value groups (a description list).
context:
  items:
    - term: "Last modified time"
      definition: "2004-12-23T23:33Z"
    - term: "Recommended update interval"
      definition: "60s"
    - term: ["Authors", "Editors"]
      definition: ["Robert Rothman", "Daniel Jackson"]
