label: "Horizontal rule"
order: 2
notes: |
  The `hr` element represents a paragraph-level thematic break, e.g., a scene change in a story, or a transition to another topic within a section of a reference book.
