label: "Article"
order: 2
notes: |
  The `article` element represents a self-contained composition that is, in principle, independently distributable or reusable, e.g. in syndication. This could be a forum post, a magazine or newspaper article, a blog entry, a user-submitted comment or any other independent item of content.
context:
  content: <!-- Article content -->
