label: "nav — Navigation"
order: 4
notes: |
  The `nav` element represents a section of a page that links to other pages or to parts within the page: a section with navigation links.
context:
  content: <!-- Navigation content -->
