label: "Aside"
order: 5
notes: |
  The `aside` element represents a section of a page that consists of content that is tangentially related to the content around the aside element, and which could be considered separate from that content. Such sections are often represented as sidebars in printed typography.
context:
  content: <!-- Aside content -->
