label: "h1 - h6"
collated: true
order: 6
notes: |
  The `h1` - `h6` elements represent headings for their sections. These elements have a rank given by the number in their name. The `h1` element is said to have the highest rank, the `h6` element has the lowest rank, and two elements with the same name have equal rank.
variants:
  - name: default
    label: "Heading 1"
    context:
      rank: 1
      content: "Heading 1"

  - name: "2"
    label: "Heading 2"
    context:
      rank: 2
      content: "Heading 2"

  - name: "3"
    label: "Heading 3"
    context:
      rank: 3
      content: "Heading 3"

  - name: "4"
    label: "Heading 4"
    context:
      rank: 4
      content: "Heading 4"

  - name: "5"
    label: "Heading 5"
    context:
      rank: 5
      content: "Heading 5"

  - name: "6"
    label: "Heading 6"
    context:
      rank: 6
      content: "Heading 6"
