label: "Annotation (underlined)"
order: 20
notes: |
  The `u` element represents a span of text with an unarticulated, though explicitly rendered, non-textual annotation, such as labeling the text as being misspelt.
