label: "Code"
order: 12
notes: |
  The `code` element represents a fragment of computer code. This could be an XML element name, a file name, a computer program, or any other string that a computer would recognise.
