label: "Address"
order: 9
notes: |
  The `address` element represents the contact information for its nearest `article` or `body` element ancestor. If that is the `body` element, then the contact information applies to the document as a whole.
context:
  content: <!-- Contact information -->
