label: "li — List item"
order: 7
notes: |
  The `li` element represents a list item. If its parent element is an `ol`, `ul`, or `menu` element, then the element is an item of the parent element's list, as defined for those elements.
context:
  content: List item text
